2021-05-01 12:07:40.017328: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cluster/apps/gcc-4.8.5/libpng-1.6.27-d6quyddan2eotsexesxufytusf27xxgz/lib:/cluster/apps/gcc-4.8.5/jpeg-9b-psjvucpx7xwkflb3meatuo6ugdtapkex/lib:/cluster/apps/gcc-4.8.5/openblas-0.2.19-w25ydbabttcfa6g76gejjkthcm3xcuv3/lib:/cluster/apps/python/3.7.1_cpu/x86_64/lib64:/cluster/apps/lsf/10.1/linux3.10-glibc2.17-x86_64/lib::
Traceback (most recent call last):
  File "main_speech_lsnn.py", line 28, in <module>
    FLAGS = arch.get_flags()
  File "/cluster/home/jubueche/BPTT-Lipschitzness/architectures.py", line 198, in get_flags
    " ".join([_format(key, get(model,key)) for key in dic])
TypeError: 'NoneType' object is not iterable
